### ISSUE TITLE
automate updating Algolia index when docs PRs are merged

### ISSUE THREAD

**Issue by ogazitt** [aserto-dev/aserto-docs#116]

**Comment by ogazitt** [comment]
The `yarn scrape` script is currently run manually when a PR is merged. It would be nice to have a github workflow for this.

**Comment by apoland** [comment]
added workflow trigger to run the scraper on push to main
https://github.com/aserto-dev/aserto-docs/blob/main/.github/workflows/scrape.yml

**Comment by ogazitt** [comment]
Would be great to have this for topaz-website as well!

**Comment by apoland** [comment]
added scraper workflow to topaz-website: 
https://github.com/aserto-dev/topaz-website/commit/fbcbf34b068c17876ec06e4e4958a9b1070674b7
